name: Npm tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run npm tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.8.0
      - run: npm install
      - run: npm test
      - name: Run ESLint
        # You may pin to the exact commit or the version.
        # uses: stefanoeb/eslint-action@0b532bcd98dbed80a59071fa8986fcf1b1715be4
        uses: stefanoeb/eslint-action@1.0.2
        with:
          # Blob of files to lint
          files: # optional, default is .
